### ISSUE TITLE
Error during install: ResolvePackageNotFound

### ISSUE THREAD

**Issue by cmzmasek** [flomock/vidhop#1]
Hi, 

I tried to install VIDHOP following your README.md

Unfortunately, when I try to execute "conda env create -f environment.yml"
I get the following error:

Collecting package metadata: done
Solving environment: failed

ResolvePackageNotFound: 
  - hdf5==1.10.4=nompi_h11e915b_1105

my conda version is: 4.6.14
OS: Ubuntu 
Python: 3.7

-Chris-

**Comment by flomock** [comment]
I rebuild the environment.yml, now its working.
I'm still wondering what caused the error as the hdf5 package (1.10.4=nompi_h11e915b_1105) was still available on the conda website.
Anyways, thanks for the notice.

If anyone has an idea what cause the problem, please let me know.
