### ISSUE TITLE
Role of CNN in arhcitecture

### ISSUE THREAD

**Issue by UCRajkumar** [flomock/vidhop#2]
In the paper, it notes "The second evaluated architecture uses two layers of convolutional neural networks (CNN) nodes,
followed by two bidirectional LSTM layers and two dense layers. In the following we will refer
to this as the CNN+LSTM architecture (see Figure 5b). Similar to the LSTM architecture, each
layer consists of 150 nodes with exception to the output layer. The idea behind this architecture
is that the CNN identifies important sequence parts (first layer), combines the short sequence
features to more complex patterns (second layer), which can then be put into context by the
LSTMs, which are able to remember previously seen patterns."

May I please know how you are able to determine that the first layer identifies the important sequences and the second combines short seqs into more complex patterns?

**Comment by flomock** [comment]
It is the expected behavior, as this is how a CNN works. But I'm not able (haven't tried) to determine the exact features.
(see Fig 1) https://mc.ai/deep-learning-book-chapter-1-introduction/
