### ISSUE TITLE
Where can I find datasets of your projects?

### ISSUE THREAD

**Issue by Logan1x** [flomock/vidhop#4]
Hey, I was looking at your project and was trying to find the individual datasets used in the project. The one that you mentioned in paper, 40k for rotavirus. Are those open to access? If yes, Where can I find them. Thanks :)

I tried to look for it in the code, but I could only find hdf5 files.

**Comment by flomock** [comment]
Hey, I thoughed it's also mentioned somewhere in the paper, or maybe it's just in the preprint due to weird journal restrictions, nonetheless:
https://osf.io/js3yw/
or the direct link:
https://mfr.de-1.osf.io/render?url=https://osf.io/h2ewz/?direct%26mode=render%26action=download%26mode=render

Let me now if this helped or not.

Greetings,
Florian

**Comment by Logan1x** [comment]
> Hey, I thoughed it's also mentioned somewhere in the paper, or maybe it's just in the preprint due to weird journal restrictions, nonetheless:
> https://osf.io/js3yw/
> or the direct link:
> https://mfr.de-1.osf.io/render?url=https://osf.io/h2ewz/?direct%26mode=render%26action=download%26mode=render
> 
> Let me now if this helped or not.
> 
> Greetings,
> Florian

Thanks, I'll look into it and get back to you if I get into any problems.

**Comment by Logan1x** [comment]
Hey @flomock, have you given open access to data of the truncated sequence you used for this project? I am stuck with truncation part and dividing into equal length part.

**Comment by flomock** [comment]
If I understand correctly, than this step should be done automatically in vidhop. 
Maybe just use the sequences directly and don't truncate anything. If this doesn't work, please let me know.

**Comment by Logan1x** [comment]
So the thing is I am trying to replicate your project and make this in simple machine learning project as my clg assignment. That's why i wanted to know .

**Comment by flomock** [comment]
I did not save the truncated sequences or the sequences divided into equal length, but I calculated them in the scripts I used before training. As this happens with previously set seeds for each random operation, this should lead to identical results and not hinder repeatability.
However if you don't want/aren't allowed to directly use my code, this is can cause minor differences if you try to replicate the data.

I would suggest to you to choose one --extension_variant and than look into [https://github.com/flomock/vidhop/blob/master/vidhop/training/train_new_model.py](url)

For the very most extension variants you wanna use something like line 505-521:
```python
length = []
for X in x_sets:
    for i in X:
      length.append(len(i))
length.sort()
maxLen = length[int(len(length) * 0.95)]
print(f"maxLen = {maxLen}")
```

and the rest you need you should find in [https://github.com/flomock/vidhop/blob/master/vidhop/DataParsing/DataParsing_main.py](url)
